// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Min_vei_Ny_i_Norge.Data;

#nullable disable

namespace Min_vei_Ny_i_Norge.Migrations
{
    [DbContext(typeof(MinVeiContekts))]
    [Migration("20230326171151_MinVeiInit")]
    partial class MinVeiInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Min_vei_Ny_i_Norge.Models.Sporsmal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sporsmalet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sporsmals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Sporsmalet = "What is your citizenship?"
                        },
                        new
                        {
                            Id = 2,
                            Sporsmalet = "What is your second citizenship?"
                        },
                        new
                        {
                            Id = 3,
                            Sporsmalet = "What is the main purpose of your stay in Norway?"
                        },
                        new
                        {
                            Id = 4,
                            Sporsmalet = "Do you have a job offer in Norway or do you plan to come as a job seeker?"
                        },
                        new
                        {
                            Id = 5,
                            Sporsmalet = "What is your expected date of arrival?"
                        },
                        new
                        {
                            Id = 6,
                            Sporsmalet = "How long do you plan to stay in Norway?"
                        },
                        new
                        {
                            Id = 7,
                            Sporsmalet = "Have you applied for a tax deduction card in Norway?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
